version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=test
      - KEYCLOAK_ADMIN_PASSWORD=test
    ports:
      - "8080:8080"
    command: start-dev